### ISSUE TITLE
How to respond to server in ack handler?

### ISSUE THREAD

**Issue by fluffynuts** [LadislavBohm/socket.io-client-core#10]
In the example project I've provided at https://github.com/fluffynuts/socket-io-core-subscribe-issue, the full pub-sub concept isn't properly implemented: a client, upon receiving data from `/consume`, should reply with an offset of how far it managed to get through the provided messages in the data packet, so that, for example, the server could send 10 messages, from offset 100 in the packet and the client may only be able to consume 5 of them and would return the value `105` so that the server would know to try messages 106-110 again. I don't see how to respond to a message coming in via `.Subscribe` - what am I missing? Socket.IO supports this kind of callback mechanism (we're using it already from node and in another implementation of a client for this pub-sub idea, written in .net, but using a different library (I'm specifically trying your library because the other appears to be flaky)

**Comment by fluffynuts** [comment]
I've updated the server in the example repo to show _where_ I would expect to be able to read a response message from the client: https://github.com/fluffynuts/socket-io-core-subscribe-issue/commit/2b488c82bbd9f6cf9e6f113c040da7a390b5bcbc

**Comment by LadislavBohm** [comment]
I see, this is not currently supported (except perhaps using raw OnPacket with it's Id). I will look at socket.io implementation of these callbacks to see how much work it would be.

**Comment by LadislavBohm** [comment]
Added support for ACK, let me know if you run into any issues.

**Comment by fluffynuts** [comment]
thanks!
