### ISSUE TITLE
Possible to connect via .Net Core 5 Console App

### ISSUE THREAD

**Issue by rbrynteson** [LadislavBohm/socket.io-client-core#17]
This might sound a bit crazy, but I have console app written in .NET Core 5 which I need to send alerts to a Socket.IO server.  I have tried this with both a local NodeJS/Express Socket.IO server and a deployed - known working server - and I always get the same error:

Socket is not running.

I'm trying to keep this very simple to start with and it's failing pretty quick.

`
static async Task Main(string[] args)
{
    Console.WriteLine("Hello World!");

    using var client = new SocketIoClient();
    await client.OpenAsync(new Uri("http://localhost:3000"));
    client.Emit("some-event", "some-data").Subscribe(ack =>
    {
        Console.WriteLine($"Callback with data: {ack.Data[0]}.");
    });
}
`

Am I just trying to do too much or should this really be able to work?

**Comment by LadislavBohm** [comment]
Hi, I think the issue might be because this library was implemented to support socket.io version 3. Current version 4 is no longer compatible and since I am no longer using socket.io in my projects I don't have much of a motivation to upgrade this library.

**Comment by rbrynteson** [comment]
Thanks for the reply, and it completely makes sense.  Have to ask, if you moved from Socket.IO, what did you move to?

**Comment by LadislavBohm** [comment]
I initially wanted to connect to 3rd party servers that were running on socket.io and the existing .NET socket.io clients were either outdated or I didn't like the way they were implemented.
Since I write back-end almost exclusively in .NET I tend to use SignalR whenever I need to work with websockets.
