### ISSUE TITLE
Can't provide path option

### ISSUE THREAD

**Issue by zapirkon** [LadislavBohm/socket.io-client-core#2]
Looks like the default path `/socket.io` is always used (based on the third line below)
Can it be something passed along as additional parameter in `OpenAsync()`?
Will it break the usage of `namespace` extracted from the uri?

```
_namespace = uri.LocalPath;
_query = string.IsNullOrEmpty(uri.Query) ? null : uri.Query.TrimStart('?');
var socketIoUri = uri.ToSocketIoWebSocketUri();
```

https://github.com/LadislavBohm/socket.io-client-core/blob/b3f642f88979a445241286aeaf1c40cf6842c53c/src/Socket.Io.Client.Core/SocketIoClient.cs#L69

**Comment by LadislavBohm** [comment]
Thanks for the report I checked socket.io documentation and hopefully it is fixed. I updated all tests to reflect this and connect to server with path. Updated nuget package will be online shortly.
