### ISSUE TITLE
Can I add this to my PHP project?

### ISSUE THREAD

**Issue by MarekJavurek** [LadislavBohm/socket.io-client-core#4]
Hi my friend, it looks like promising project, but can I add this lib to my PHP project? 

Thans for reply in advace

**EDIT:**
this is the place where I want to use your lib, please help!
![image](https://user-images.githubusercontent.com/405034/76747987-505a7d00-677a-11ea-8760-35c5a514c652.png)

**EDIT 2:**
It liiks line promising project but you are not responding @LadislavBohm !!!!???

**EDIT 3:**
OK, I just found new lib **jQuery**, i will solve my problem with this new lib. They have great support!

**Comment by LadislavBohm** [comment]
Hello, my friend, I am afraid you are a bit lost. This repository hosts client for C# programming language as stated in a title of readme:
![image](https://user-images.githubusercontent.com/4920886/76750522-bf39d500-677e-11ea-9f05-31c3a3f184d1.png)

Please refer to some of your PHP friends, they might be able to help you with that.

**Comment by MarekJavurek** [comment]
Thanks for closing issue. You wasnt helpfull to me anyway. Bye
